{% set version = "2.1.1" %}

package:
  name: jupyterhub-feedstock
  version: {{ version }}

source:
  fn: jupyterhub-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: 386ae16dba48cb48f593bd1108cc01fb3c500cca607afae13e35d96461d7a19c

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

outputs:
  - name: jupyterhub-base
    build:
      noarch: python
      script: |
        python -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - alembic
        - async_generator >=1.9
        - certipy >=0.1.2
        - entrypoints
        - jinja2 >=2.11.0
        - jupyter_telemetry >=0.1.0
        - oauthlib >=3.0
        - pamela
        - prometheus_client >=0.4.0
        - psutil
        - pycurl
        - python-dateutil
        - requests
        - sqlalchemy >=1.1
        - tornado >=5.1
        - traitlets >=4.3.2

    test:
      imports:
        - jupyterhub
        - jupyterhub.apihandlers
        - jupyterhub.handlers
        - jupyterhub.tests
        - jupyterhub.app
      commands:
        - python -m jupyterhub --help-all
        - test -f $PREFIX/share/jupyterhub/templates/page.html
        - test -f $PREFIX/share/jupyterhub/static/components/jquery/dist/jquery.min.js
        - test -f $PREFIX/share/jupyterhub/static/css/style.min.css
        - test -f $PREFIX/share/jupyterhub/static/js/home.js

  - name: jupyterhub-singleuser
    build:
      noarch: generic
    requirements:
      run:
        - python >=3.6
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - jupyterlab >=3.1
    test:
      imports:
        - jupyterhub.singleuser
      commands:
        - python -m jupyterhub.singleuser --help-all

  - name: jupyterhub
    build:
      noarch: generic
    requirements:
      run:
        - python
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - configurable-http-proxy >=4
        - nodejs >=12
    test:
      imports:
        - jupyterhub
      commands:
        - python -m jupyterhub --help-all
        - configurable-http-proxy --help

about:
  home: https://github.com/jupyterhub/jupyterhub
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
    - blink1073
    - consideRatio
    - manics
